// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgdkw0VFZPkL1mAEwrBNKJp_bYF2WMqa0',
    appId: '1:249326599146:web:8f40017ff42e81e0b29093',
    messagingSenderId: '249326599146',
    projectId: 'labelcious',
    authDomain: 'labelcious.firebaseapp.com',
    storageBucket: 'labelcious.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSF38O1esOai6hJ9r9Qe4jIEq03T7eKuA',
    appId: '1:249326599146:android:30cd2ff42c673f4cb29093',
    messagingSenderId: '249326599146',
    projectId: 'labelcious',
    storageBucket: 'labelcious.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJc6zRtIU16_KN0xgTrJ64TdzEXplezGo',
    appId: '1:249326599146:ios:cdb2839bf7f82053b29093',
    messagingSenderId: '249326599146',
    projectId: 'labelcious',
    storageBucket: 'labelcious.appspot.com',
    iosClientId: '249326599146-gkklr69nss9v9b2ptcgsphcq6j097jdl.apps.googleusercontent.com',
    iosBundleId: 'com.labelvie.labelcious.mobilelabelcious',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJc6zRtIU16_KN0xgTrJ64TdzEXplezGo',
    appId: '1:249326599146:ios:ab197b2404d04e22b29093',
    messagingSenderId: '249326599146',
    projectId: 'labelcious',
    storageBucket: 'labelcious.appspot.com',
    iosClientId: '249326599146-4fs4hutbff95iu067t79sqr670b77htj.apps.googleusercontent.com',
    iosBundleId: 'com.labelvie.labelcious.mobilelabelcious.RunnerTests',
  );
}
